source("config.R")

message("Running analysis/01_clean_data.R")
source("analysis/01_clean_data.R")
message("Running analysis/02_descriptive_tables.R")
source("analysis/02_descriptive_tables.R")
message("Running analysis/03_build_multistate_data.R")
source("analysis/03_build_multistate_data.R")
message("Running analysis/04_fit_transition_models.R")
source("analysis/04_fit_transition_models.R")
message("Running analysis/05_transition_probabilities.R")
source("analysis/05_transition_probabilities.R")
message("Running analysis/06_rpre_death_model_check.R")
source("analysis/06_rpre_death_model_check.R")
message("Running analysis/07_validate_multistate_data.R")
source("analysis/07_validate_multistate_data.R")
