source("run_core.R")

message("Running analysis/08_sensitivity_analyses.R")
source("analysis/08_sensitivity_analyses.R")
message("Running analysis/09_bootstrap_probabilities.R")
source("analysis/09_bootstrap_probabilities.R")
message("Running analysis/12_year_center_sensitivity.R")
source("analysis/12_year_center_sensitivity.R")
message("Running analysis/13_propensity_score_feasibility.R")
source("analysis/13_propensity_score_feasibility.R")
message("Running analysis/14_overlap_weighted_cox.R")
source("analysis/14_overlap_weighted_cox.R")
message("Running analysis/15_overlap_weighted_probabilities.R")
source("analysis/15_overlap_weighted_probabilities.R")
message("Running analysis/16_implant_specific_revision.R")
source("analysis/16_implant_specific_revision.R")
message("Running analysis/17_propensity_score_diagnostics.R")
source("analysis/17_propensity_score_diagnostics.R")
message("Running analysis/18_complete_pathway_probability.R")
source("analysis/18_complete_pathway_probability.R")
message("Running analysis/19_complete_pathway_figure.R")
source("analysis/19_complete_pathway_figure.R")
message("Running analysis/20_revision_selection_check.R")
source("analysis/20_revision_selection_check.R")
message("Running analysis/21_history_dependence_after_p2.R")
source("analysis/21_history_dependence_after_p2.R")
message("Running analysis/22_age_at_p2_sensitivity.R")
source("analysis/22_age_at_p2_sensitivity.R")
message("Running analysis/23_validate_probability_update.R")
source("analysis/23_validate_probability_update.R")
message("Running analysis/24_product_integral_comparison.R")
source("analysis/24_product_integral_comparison.R")
message("Running analysis/10_make_main_figures.R")
source("analysis/10_make_main_figures.R")
message("Running analysis/11_audit_outputs.R")
source("analysis/11_audit_outputs.R")
message("Running analysis/25_export_final_outputs.R")
source("analysis/25_export_final_outputs.R")
