source("config.R")

# Propensity-score diagnostics for the overlap-weighted sensitivity analysis.
# This script is intentionally kept separate from the main analysis workflow.
# It should be run after analysis/13_propensity_score_feasibility.R and
# analysis/15_overlap_weighted_probabilities.R.

message("Propensity-score diagnostics are generated by the preceding overlap-weighting scripts.")
